### ISSUE TITLE
Color Temperature/CCT support?

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [bokub/rgb-light-card#39] opened 2021-01-26 20:22 UTC
I've got a bunch of adjustable color temperature bulbs and would love to be able to adjust their values with a card like this.

**Comment by Jan-Ka** [comment] 2021-01-26 21:20
Hi, not the maintainer but just stumbled over your comment. You can adjust your bulbs color temperature with something like this:

```yaml
entity: light.my_light
type: 'custom:rgb-light-card'
colors:
  - kelvin: 3500
    transition: 1
  - kelvin: 5000
    transition: 1
  - kelvin: 2700
    transition: 1
```

Tested this with Athom (Tasmota) Bulbs but as long as you can change the color temp in hassio, you should be able to do it with this card.

**Comment by atrv7** [comment] 2021-01-27 00:20
This works to change the rgb values to match those color temperatures but I just tested with RGBW led strips and it doesnt seem to control the White channel at all. Any ideas?

**Comment by bokub** [comment] 2021-01-27 07:24
Looks like a duplicate of #25..

**Comment by bokub** [comment] 2021-04-21 09:14
I'm closing this issue

**Closed by bokub** 2021-04-21 09:14 UTC
