### ISSUE TITLE
[Feature request] Have hide_when_off also work when light is unreachable

### ISSUE THREAD

**Issue by bigmak40** [bokub/rgb-light-card#41] opened 2021-02-05 14:06 UTC
I have a few lights that are controlled by light switches on the wall still (I'll fix it some day), so when the wall switch is powered off the bulbs are unreachable.

hide_when_off does not hide the row when it's in the unreachable state.

Recommend either adding the condition to hide_when_off or adding a new variable, hide_when_unreachable.

**Comment by bokub** [comment] 2021-02-05 14:23
Duplicate of #34

**Closed by bokub** 2021-02-05 14:23 UTC

**Comment by bigmak40** [comment] 2021-02-05 14:28
My bad, thanks!

**Comment by bokub** [comment] 2021-04-21 09:13
Fixed in 1.8.0 :tada:
